Repository angristan/openvpn-install, pull requests merged in 2018-09, with the labels that each got.

#288 Add self-hosted DNS resolver (Unbound)
  README.md
  openvpn-install.sh
Labels: enhancement

#238 Add IPv6 NAT support
  README.md
  openvpn-install.sh
Labels: enhancement, need feedback

#291 Rework iptables handling
  README.md
  openvpn-install.sh
Labels: enhancement

#294 Rework and cleanup systemd service handling
  openvpn-install.sh
Labels: bug

#293 Refactoring, cleanup and fixes
  README.md
  openvpn-install.sh
Labels: enhancement

#187 Improve Debian/Ubuntu version checking
  openvpn-install.sh
Labels: enhancement

#303 Add Arch Linux support
  README.md
  openvpn-install.sh
Labels: enhancement

#301 Update easy-rsa to 3.0.5
  openvpn-install.sh
Labels: enhancement

#304 Added iOS official client
  README.md
Labels: enhancement, need feedback
