Repository angristan/openvpn-install, pull requests merged in 2020-04, with the labels that each got.

#598 Comments about DNS
  openvpn-install.sh
Labels: enhancement

#611 Move FAQ from wiki to git to allow contributions
  .github/ISSUE_TEMPLATE.md
  FAQ.md
  README.md
Labels: wiki

#612 Uninstallation: restart unbound only if not removed
  openvpn-install.sh
Labels: enhancement

#591 Change = conditional to ==
  openvpn-install.sh
Labels: enhancement

#608 Improve sed line deletion
  openvpn-install.sh
Labels: enhancement

#609 Add support for client-configuration-dir
  openvpn-install.sh
Labels: enhancement

#627 Add FAQ for DNS Leaks blocking
  FAQ.md
Labels: docs

#626 Add FAQ entry for sysctl and iptables changes
  FAQ.md
Labels: docs

#629 Add FAQ for router clients
  FAQ.md
Labels: docs

#631 Add FAQ for client-to-client
  FAQ.md
Labels: docs

#592 Idempotent in headless mode
  README.md
  openvpn-install.sh
Labels: enhancement

#607 Remove not necessary code
  openvpn-install.sh
Labels: enhancement

#628 Ignore block-outside-dns in Linux
  openvpn-install.sh
Labels: bug fix

#632 FAQ: Update DNS not working question
  FAQ.md
Labels: docs

#315 Add secp256k1 option
  README.md
  openvpn-install.sh
Labels: enhancement

#638 style(script): format with shfmt
  openvpn-install.sh
Labels: enhancement

#555 Fix deletion of selinux policy
  openvpn-install.sh
Labels: bug fix, to-test

#589 Simplify detection of public IP4, add IPv6
  openvpn-install.sh
Labels: enhancement, to-test

#599 Get DNS-IPv6 from current system resolvers
  openvpn-install.sh
Labels: enhancement

#630 Add FAQ to access remote LAN
  FAQ.md
Labels: docs

#643 ci(workflow): run script in headless mode on VMs
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement

#601 Add IPv6 INPUT on incomming port
  openvpn-install.sh
Labels: enhancement

#600 Add DNS IPv6 for self-hosted DNS Resolver
  openvpn-install.sh
Labels: enhancement
