Repository angristan/openvpn-install, pull requests merged in 2023-01, with the labels that each got.

#1066 Fixed issue with ifconfig.co
  openvpn-install.sh
Labels: enhancement

#1083 Update FAQ with IPv6 prefix policies for ULA addresses
  FAQ.md
Labels: docs

#1096 Update easy-rsa to 3.1.2 and fix compatibility with Ubuntu 22.04
  .github/workflows/test.yml
  openvpn-install.sh
Labels: bug fix
